// Generated by CoffeeScript 1.6.3
(function() {
  angular.module('boom', []).config([
    '$routeProvider', function($routeProvider) {
      return $routeProvider.when('/', {
        templateUrl: 'templates/home.html',
        controller: TestCtl
      }).when('/a', {
        templateUrl: 'templates/test.html',
        controller: TestCtl
      }).when('/b', {
        templateUrl: 'templates/test.html',
        controller: TestCtl
      }).when('/c', {
        templateUrl: 'templates/test.html',
        controller: TestCtl
      }).otherwise({
        redirectTo: '/'
      });
    }
  ]);

  this.TestCtl = function($scope) {
    return $scope.name = 'knife';
  };

}).call(this);
